spring.application.name=scheduler
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create


server.port=${PORT:8080}

brevo.api.key=${BREVO_API_KEY}

# Project Tracking Feature Configuration
project.upload.dir=${UPLOAD_DIR:C:/uploads}
server.servlet.multipart.max-file-size=50MB
server.servlet.multipart.max-request-size=50MB
spring.web.resources.static-locations=classpath:/static/,file:${UPLOAD_DIR:C:/uploads}/

quotation.pdf-dir=C:/uploads/quotations

spring.mvc.static-path-pattern=/uploads/**