spring.application.name=scheduler
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mcharlesmudau@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Project Tracking Feature Configuration
project.upload.dir=C:/uploads/projects
server.servlet.multipart.max-file-size=50MB
server.servlet.multipart.max-request-size=50MB
spring.web.resources.static-locations=classpath:/static/,file:./uploads/

quotation.pdf-dir=C:/uploads/quotations